web:
  build: .
  command: foreman start
  volumes:
    - .:/app
  ports:
    - "5000:5000"
  links:
    - postgres

postgres:
  image: postgres:9.4
  ports:
    - "5432"
  volumes:
    - /var/lib/postgresql/data